fix: add js

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -74,66 +74,65 @@ jobs:
           pkg-config --define-prefix --cflags --libs taglib # for debugging
           go test -shuffle=on -race -cover ./... -v
 
-#  js:
-#    name: Build JS bundle
-#    runs-on: ubuntu-latest
-#    env:
-#      NODE_OPTIONS: "--max_old_space_size=4096"
-#    steps:
-#      - uses: actions/checkout@v4
-#      - uses: actions/setup-node@v4
-#        with:
-#          node-version: 20
-#          cache: "npm"
-#          cache-dependency-path: "**/package-lock.json"
-#
-#      - name: npm install dependencies
-#        run: |
-#          cd ui
-#          npm ci
-#
-#      - name: npm lint
-#        run: |
-#          cd ui
-#          npm run check-formatting && npm run lint
-#
-#      - name: npm test
-#        run: |
-#          cd ui
-#          npm test
-#
-#      - name: npm build
-#        run: |
-#          cd ui
-#          npm run build
-#
+  js:
+    name: Test JS code
+    runs-on: ubuntu-latest
+    env:
+      NODE_OPTIONS: "--max_old_space_size=4096"
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: "npm"
+          cache-dependency-path: "**/package-lock.json"
+
+      - name: npm install dependencies
+        run: |
+          cd ui
+          npm ci
+
+      - name: npm lint
+        run: |
+          cd ui
+          npm run check-formatting && npm run lint
+
+      - name: npm test
+        run: |
+          cd ui
+          npm test
+
+      - name: npm build
+        run: |
+          cd ui
+          npm run build
+
 #      - uses: actions/upload-artifact@v4
 #        with:
 #          name: js-bundle
 #          path: ui/build
 #          retention-days: 7
 #
-#  i18n-lint:
-#    name: Lint i18n files
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v4
-#      - run: |
-#          set -e
-#          for file in resources/i18n/*.json; do
-#            echo "Validating $file"
-#            if ! jq empty "$file" 2>error.log; then
-#              error_message=$(cat error.log)
-#              line_number=$(echo "$error_message" | grep -oP 'line \K[0-9]+')
-#              echo "::error file=$file,line=$line_number::$error_message"
-#              exit 1
-#            fi
-#          done
+  i18n-lint:
+    name: Lint i18n files
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - run: |
+          set -e
+          for file in resources/i18n/*.json; do
+            echo "Validating $file"
+            if ! jq empty "$file" 2>error.log; then
+              error_message=$(cat error.log)
+              line_number=$(echo "$error_message" | grep -oP 'line \K[0-9]+')
+              echo "::error file=$file,line=$line_number::$error_message"
+              exit 1
+            fi
+          done
 
   build:
     name: Build
-    needs: [go, go-lint]
-#    needs: [js, go, go-lint, i18n-lint]
+    needs: [js, go, go-lint, i18n-lint]
     strategy:
       matrix:
         platform: [ linux/amd64, linux/arm64, linux/arm/v5, linux/arm/v6, linux/arm/v7, linux/386, darwin/amd64, darwin/arm64, windows/amd64, windows/386 ]
