test: is_release

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -11,127 +11,127 @@ on:
 
 env:
   CROSS_TAGLIB_VERSION: "2.0.2-1"
-  IS_RELEASE: startsWith(github.ref, 'refs/tags/')
+  IS_RELEASE: ${{ !startsWith(github.ref, 'refs/tags/') }}
 
 jobs:
-  go-lint:
-    name: Lint Go code
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Download TagLib
-        run: |
-          FILE=taglib-linux-amd64.tar.gz
-          wget https://github.com/navidrome/cross-taglib/releases/download/v${{env.CROSS_TAGLIB_VERSION}}/${FILE}
-          mkdir taglib
-          tar -xzf ${FILE} -C taglib
-          rm ${FILE}
-          PKG_CONFIG_PREFIX=$(pwd)/taglib
-          echo "PKG_CONFIG_PREFIX=${PKG_CONFIG_PREFIX}" >> $GITHUB_ENV
-          echo "PKG_CONFIG_PATH=${PKG_CONFIG_PREFIX}/lib/pkgconfig" >> $GITHUB_ENV
-
-      - name: golangci-lint
-        uses: golangci/golangci-lint-action@v6
-        with:
-          version: latest
-          problem-matchers: true
-          args: --timeout 2m
-
-      - name: Run go goimports
-        run: go run golang.org/x/tools/cmd/goimports@latest -w `find . -name '*.go' | grep -v '_gen.go$'`
-      - run: go mod tidy
-      - name: Verify no changes from goimports and go mod tidy
-        run: |
-          git status --porcelain
-          if [ -n "$(git status --porcelain)" ]; then
-            echo 'To fix this check, run "make format" and commit the changes'
-            exit 1
-          fi
-
-  go:
-    name: Test Go code
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check out code into the Go module directory
-        uses: actions/checkout@v4
-
-      - name: Download TagLib
-        run: |
-          FILE=taglib-linux-amd64.tar.gz
-          wget https://github.com/navidrome/cross-taglib/releases/download/v${{env.CROSS_TAGLIB_VERSION}}/${FILE}
-          mkdir taglib
-          tar -xzf ${FILE} -C taglib
-          rm ${FILE}
-          PKG_CONFIG_PREFIX=$(pwd)/taglib
-          echo "PKG_CONFIG_PREFIX=${PKG_CONFIG_PREFIX}" >> $GITHUB_ENV
-          echo "PKG_CONFIG_PATH=${PKG_CONFIG_PREFIX}/lib/pkgconfig" >> $GITHUB_ENV
-
-      - run: |
-          ./.github/workflows/git-tags.sh
-          git tag -l
-
-      - name: Download dependencies
-        run: go mod download
-
-      - name: Test
-        run: |
-          pkg-config --define-prefix --cflags --libs taglib # for debugging
-          go test -shuffle=on -race -cover ./... -v
-
-  js:
-    name: Test JS code
-    runs-on: ubuntu-latest
-    env:
-      NODE_OPTIONS: "--max_old_space_size=4096"
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-node@v4
-        with:
-          node-version: 20
-          cache: "npm"
-          cache-dependency-path: "**/package-lock.json"
-
-      - name: npm install dependencies
-        run: |
-          cd ui
-          npm ci
-
-      - name: npm lint
-        run: |
-          cd ui
-          npm run check-formatting && npm run lint
-
-      - name: npm test
-        run: |
-          cd ui
-          npm test
-
-      - name: npm build
-        run: |
-          cd ui
-          npm run build
-
-  i18n-lint:
-    name: Lint i18n files
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - run: |
-          set -e
-          for file in resources/i18n/*.json; do
-            echo "Validating $file"
-            if ! jq empty "$file" 2>error.log; then
-              error_message=$(cat error.log)
-              line_number=$(echo "$error_message" | grep -oP 'line \K[0-9]+')
-              echo "::error file=$file,line=$line_number::$error_message"
-              exit 1
-            fi
-          done
-
+#  go-lint:
+#    name: Lint Go code
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v4
+#
+#      - name: Download TagLib
+#        run: |
+#          FILE=taglib-linux-amd64.tar.gz
+#          wget https://github.com/navidrome/cross-taglib/releases/download/v${{env.CROSS_TAGLIB_VERSION}}/${FILE}
+#          mkdir taglib
+#          tar -xzf ${FILE} -C taglib
+#          rm ${FILE}
+#          PKG_CONFIG_PREFIX=$(pwd)/taglib
+#          echo "PKG_CONFIG_PREFIX=${PKG_CONFIG_PREFIX}" >> $GITHUB_ENV
+#          echo "PKG_CONFIG_PATH=${PKG_CONFIG_PREFIX}/lib/pkgconfig" >> $GITHUB_ENV
+#
+#      - name: golangci-lint
+#        uses: golangci/golangci-lint-action@v6
+#        with:
+#          version: latest
+#          problem-matchers: true
+#          args: --timeout 2m
+#
+#      - name: Run go goimports
+#        run: go run golang.org/x/tools/cmd/goimports@latest -w `find . -name '*.go' | grep -v '_gen.go$'`
+#      - run: go mod tidy
+#      - name: Verify no changes from goimports and go mod tidy
+#        run: |
+#          git status --porcelain
+#          if [ -n "$(git status --porcelain)" ]; then
+#            echo 'To fix this check, run "make format" and commit the changes'
+#            exit 1
+#          fi
+#
+#  go:
+#    name: Test Go code
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Check out code into the Go module directory
+#        uses: actions/checkout@v4
+#
+#      - name: Download TagLib
+#        run: |
+#          FILE=taglib-linux-amd64.tar.gz
+#          wget https://github.com/navidrome/cross-taglib/releases/download/v${{env.CROSS_TAGLIB_VERSION}}/${FILE}
+#          mkdir taglib
+#          tar -xzf ${FILE} -C taglib
+#          rm ${FILE}
+#          PKG_CONFIG_PREFIX=$(pwd)/taglib
+#          echo "PKG_CONFIG_PREFIX=${PKG_CONFIG_PREFIX}" >> $GITHUB_ENV
+#          echo "PKG_CONFIG_PATH=${PKG_CONFIG_PREFIX}/lib/pkgconfig" >> $GITHUB_ENV
+#
+#      - run: |
+#          ./.github/workflows/git-tags.sh
+#          git tag -l
+#
+#      - name: Download dependencies
+#        run: go mod download
+#
+#      - name: Test
+#        run: |
+#          pkg-config --define-prefix --cflags --libs taglib # for debugging
+#          go test -shuffle=on -race -cover ./... -v
+#
+#  js:
+#    name: Test JS code
+#    runs-on: ubuntu-latest
+#    env:
+#      NODE_OPTIONS: "--max_old_space_size=4096"
+#    steps:
+#      - uses: actions/checkout@v4
+#      - uses: actions/setup-node@v4
+#        with:
+#          node-version: 20
+#          cache: "npm"
+#          cache-dependency-path: "**/package-lock.json"
+#
+#      - name: npm install dependencies
+#        run: |
+#          cd ui
+#          npm ci
+#
+#      - name: npm lint
+#        run: |
+#          cd ui
+#          npm run check-formatting && npm run lint
+#
+#      - name: npm test
+#        run: |
+#          cd ui
+#          npm test
+#
+#      - name: npm build
+#        run: |
+#          cd ui
+#          npm run build
+#
+#  i18n-lint:
+#    name: Lint i18n files
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v4
+#      - run: |
+#          set -e
+#          for file in resources/i18n/*.json; do
+#            echo "Validating $file"
+#            if ! jq empty "$file" 2>error.log; then
+#              error_message=$(cat error.log)
+#              line_number=$(echo "$error_message" | grep -oP 'line \K[0-9]+')
+#              echo "::error file=$file,line=$line_number::$error_message"
+#              exit 1
+#            fi
+#          done
+#
   build:
     name: Build
-    needs: [js, go, go-lint, i18n-lint]
+#    needs: [js, go, go-lint, i18n-lint]
     strategy:
       matrix:
         platform: [ linux/amd64, linux/arm64, linux/arm/v5, linux/arm/v6, linux/arm/v7, linux/386, darwin/amd64, darwin/arm64, windows/amd64, windows/386 ]
@@ -143,46 +143,46 @@ jobs:
           PLATFORM=$(echo ${{ matrix.platform }} | tr '/' '_')
           echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
 
-      - name: Set up QEMU
-        id: qemu
-        uses: docker/setup-qemu-action@v3
+#      - name: Set up QEMU
+#        id: qemu
+#        uses: docker/setup-qemu-action@v3
+#
+#      - name: Set up Docker Buildx
+#        id: buildx
+#        uses: docker/setup-buildx-action@v3
+#
+#      - uses: actions/checkout@v4
+#
+#      - name: Get Git Version
+#        run: |
+#          GIT_TAG=$(git tag --sort=-committerdate | head -n 1)
+#          if [ -n "$GIT_TAG" ]; then
+#            GIT_TAG=${GIT_TAG}-SNAPSHOT
+#            echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
+#          fi
+#          git describe --dirty --always --tags
+#          git tag --sort=-committerdate | head -n 1
+#          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
+#
+#      - name: Build
+#        uses: docker/build-push-action@v6
+#        env:
+#          DOCKER_BUILD_SUMMARY: false
+#        with:
+#          context: .
+#          file: Dockerfile
+#          platforms: ${{ matrix.platform }}
+#          outputs: |
+#            type=local,dest=./output/${{ env.PLATFORM }}
+#          target: binary
+#          build-args: |
+#            GIT_SHA=${{ env.GIT_SHA }}
+#            GIT_TAG=${{ env.GIT_TAG }}
+#            CROSS_TAGLIB_VERSION=${{ env.CROSS_TAGLIB_VERSION }}
 
-      - name: Set up Docker Buildx
-        id: buildx
-        uses: docker/setup-buildx-action@v3
-
-      - uses: actions/checkout@v4
-
-      - name: Get Git Version
-        run: |
-          GIT_TAG=$(git tag --sort=-committerdate | head -n 1)
-          if [ -n "$GIT_TAG" ]; then
-            GIT_TAG=${GIT_TAG}-SNAPSHOT
-            echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
-          fi
-          git describe --dirty --always --tags
-          git tag --sort=-committerdate | head -n 1
-          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
-
-      - name: Build
-        uses: docker/build-push-action@v6
-        env:
-          DOCKER_BUILD_SUMMARY: false
-        with:
-          context: .
-          file: Dockerfile
-          platforms: ${{ matrix.platform }}
-          outputs: |
-            type=local,dest=./output/${{ env.PLATFORM }}
-          target: binary
-          build-args: |
-            GIT_SHA=${{ env.GIT_SHA }}
-            GIT_TAG=${{ env.GIT_TAG }}
-            CROSS_TAGLIB_VERSION=${{ env.CROSS_TAGLIB_VERSION }}
-
-#      - run: |
-#          mkdir -p ./output/${{ env.PLATFORM }}
-#          echo ${{ env.PLATFORM }} > ./output/${{ env.PLATFORM }}/navidrome
+      - run: |
+          mkdir -p ./output/${{ env.PLATFORM }}
+          echo ${{ env.PLATFORM }} > ./output/${{ env.PLATFORM }}/navidrome
 
       - uses: actions/upload-artifact@v4
         with:
@@ -205,11 +205,16 @@ jobs:
 
       - run: ls -lR ./binaries
 
+      - run: |
+          echo "IS_RELEASE=${{ env.IS_RELEASE }}" 
+          echo "release --clean -f release/goreleaser.yml ${{ env.IS_RELEASE == 'false' && '' || '--skip=publish --snapshot' }}"
+          echo "release --clean -f release/goreleaser.yml ${{ env.IS_RELEASE == 'true' && '' || '--skip=publish --snapshot' }}"
+
       - name: Run GoReleaser
         uses: goreleaser/goreleaser-action@v6
         with:
           version: '~> v2'
-          args: ${{ env.IS_RELEASE && 'release --clean -f release/goreleaser.yml' || 'release --clean --skip=publish --snapshot -f release/goreleaser.yml' }}
+          args: "release --clean -f release/goreleaser.yml ${{ env.IS_RELEASE == 'true' && '' || '--skip=publish --snapshot -f release/goreleaser.yml' }}"
 #          env:
 #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
